name: Anirvan's blog
description: An engineer's misadventures
meta_description: "A code blog written by Anirvan Mandal about things he finds while working"
title: Anirvan Mandal's Blog

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'https://blog.anirvanm.com'
permalink: /:year/:month/:day/:title:output_ext
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

tag_page_layout: tag_page
tag_page_dir: tag

# Details for the RSS feed generator
url:            'http://blog.anirvanm.com'
author:         'Anirvan Mandal'
